/* config.js - App version and strategy definitions */

const APP_VERSION = '1.22.0';

const STRATEGIES = [
    {
        id: 'one_more_one_less',
        name: 'One More, One Less',
        shortName: '+1 / -1',
        description: 'Add or subtract 1 to get the next or previous number.',
        order: 1,
        unlockRequires: null,
    },
    {
        id: 'know_about_zero',
        name: 'Know About 0',
        shortName: '± 0',
        description: 'Adding or subtracting 0 leaves the number the same.',
        order: 2,
        unlockRequires: null,
    },
    {
        id: 'two_more_two_less',
        name: 'Two More, Two Less',
        shortName: '+2 / -2',
        description: 'Add or subtract 2, think odds and evens.',
        order: 3,
        unlockRequires: 'one_more_one_less',
    },
    {
        id: 'five_and_a_bit',
        name: 'Five and a Bit',
        shortName: '5 + ?',
        description: 'Numbers 6-9 are made of five and a bit.',
        order: 4,
        unlockRequires: null,
    },
    {
        id: 'number_neighbours',
        name: 'Number Neighbours',
        shortName: 'Neighbours',
        description: 'Adjacent numbers differ by 1, adjacent odds/evens by 2.',
        order: 5,
        unlockRequires: 'two_more_two_less',
    },
    {
        id: 'doubles',
        name: 'Doubles & Near Doubles',
        shortName: 'Doubles',
        description: 'Memorise doubles, then use them for near doubles.',
        order: 6,
        unlockRequires: 'one_more_one_less',
    },
    {
        id: 'number_10_facts',
        name: 'Number 10 Fact Families',
        shortName: '10 Facts',
        description: 'Pairs that add to 10 and related subtractions.',
        order: 7,
        unlockRequires: null,
    },
    {
        id: 'seven_tree_nine_square',
        name: '7 Tree & 9 Square',
        shortName: '7 & 9',
        description: 'Visual images for tricky fact families of 7 and 9.',
        order: 8,
        unlockRequires: 'five_and_a_bit',
    },
    {
        id: 'swap_it',
        name: 'Swap It',
        shortName: 'Swap',
        description: 'The order of addends does not change the sum.',
        order: 9,
        unlockRequires: null,
    },
    {
        id: 'ten_and_a_bit',
        name: 'Ten and a Bit',
        shortName: '10 + ?',
        description: 'Numbers 11-20 are made of ten and a bit.',
        order: 10,
        unlockRequires: 'number_10_facts',
    },
    {
        id: 'make_ten_then',
        name: 'Make Ten and Then...',
        shortName: 'Make 10',
        description: 'Cross the 10 boundary by making 10 first.',
        order: 11,
        unlockRequires: 'ten_and_a_bit',
    },
    {
        id: 'adjust_it',
        name: 'Adjust It',
        shortName: 'Adjust',
        description: 'Calculate by adjusting from a known fact.',
        order: 12,
        unlockRequires: 'make_ten_then',
    },
];
