/* versions.js - Version history archive
   Each release is archived here so users can view the changelog in-app.
   Archived source snapshots live in /versions/{version}/ folders.
   Add a new entry at the TOP of the array for each commit/release.
*/

const VERSION_HISTORY = [
    {
        version: '1.19.0',
        date: '2026-02-16',
        title: 'Embedded Expansion + PWA/Cloud Sync Foundation',
        current: true,
        changes: [
            'Added: Firebase Firestore sync bridge with graceful fallback to local-only mode',
            'Improved: Player selection now attempts cloud-to-local restore before entering home',
            'Added: Expansion standalone quick link and embedded expansion shell support in the main app',
            'Improved: Service worker now pre-caches expansion assets and expansion HTML offline fallback',
            'Updated: Expansion semantic version to v2.27.0 with release notes',
        ],
    },
    {
        version: '1.18.0',
        date: '2026-02-15',
        title: 'Keypad Order + No-Cutoff Mobile Layout',
        current: false,
        changes: [
            'Updated: Expansion keypad ordering now matches phone/index layout (1-2-3 top row)',
            'Improved: Quiz layout avoids keypad cutoff on short/mobile screens using compact spacing and dynamic viewport height',
            'Improved: Numpad safe-area handling simplified to prevent bottom clipping',
            'Updated: Expansion semantic version to v2.26.0 with release notes',
        ],
    },
    {
        version: '1.17.0',
        date: '2026-02-15',
        title: 'Focus Mode Ultra-Compact Layout Pass',
        current: false,
        changes: [
            'Improved: Focus mode spacing compressed further across problem area, keypad, feedback, and headers',
            'Improved: Adaptive equation sizing with tighter vertical rhythm for short/mobile screens',
            'Improved: Session mini-stats auto-hide on short viewports to keep solve controls above fold',
            'Updated: Expansion semantic version to v2.25.0 with release notes',
        ],
    },
    {
        version: '1.16.0',
        date: '2026-02-15',
        title: 'Core + Expansion Navigation Bridge Stabilization',
        current: false,
        changes: [
            'Added: Core app/expansion embedded navigation bridge with method-selection interstitial',
            'Improved: Unified screen transitions now clear transient quiz hint/visual state',
            'Improved: Global back handling for expansion and core screens',
            'Updated: Expansion semantic version to v2.24.0 with release notes',
        ],
    },
    {
        version: '1.15.0',
        date: '2026-02-15',
        title: 'Denser Focus Mode + Keypad-First Submit Flow',
        current: false,
        changes: [
            'Improved: Practice-focus spacing tightened so more solve UI remains above the fold on mobile',
            'Updated: Facts, levels, and word-problem flows now use keypad-first submit with integrated ✓ action',
            'Improved: Keypad buttons enlarged and styled for better thumb accuracy',
            'Improved: Auto-next and auto-focus are now quick toggles inside the focus overflow menu',
            'Updated: Expansion semantic version to v2.23.0 with release notes',
        ],
    },
    {
        version: '1.14.0',
        date: '2026-02-15',
        title: 'Mobile Input & Scroll UX Improvements',
        current: false,
        changes: [
            'Improved: Word problem layout puts answer input earlier to reduce scrolling before answering',
            'Added: Touch keypad for word problems, facts practice, and progressive levels practice',
            'Improved: Word problem mobile sticky answer area for faster answer entry',
            'Improved: Compact mobile spacing in practice screens to reduce vertical scrolling',
            'Updated: Expansion semantic version to v2.22.0 with release notes',
        ],
    },
    {
        version: '1.13.0',
        date: '2026-02-15',
        title: 'Visual Demo Interaction Upgrade + Mobile Layout Fixes',
        current: false,
        changes: [
            'Added: Selectable number-line interaction so learners can tap landing points and show jump strategy',
            'Added: Base-10 design style tabs (Classic, Pastel, High Contrast, Outline)',
            'Improved: Part-whole interactive panel with missing-part and missing-whole modes',
            'Updated: Word problem highlight key moved above highlighted text for better hint usability',
            'Improved: Responsive layout to reduce horizontal overflow on iPad/iPhone',
            'Updated: Expansion semantic version to v2.21.0 with release notes',
        ],
    },
    {
        version: '1.12.0',
        date: '2026-02-15',
        title: 'Interactive Visual Demo Knowledge Checks',
        current: false,
        changes: [
            'Updated: Ten-frame terminology from Section A/B to Part A/B with red/blue colour mapping',
            'Added: Number line interactive question and answer check panel',
            'Added: Base-10 place-value interactive check with hundreds/tens/ones inputs',
            'Added: Part-whole missing-part interactive check workflow',
            'Updated: Expansion semantic version to v2.20.0 with release notes',
        ],
    },
    {
        version: '1.11.0',
        date: '2026-02-15',
        title: 'Interactive Ten-Frame Visual Demo',
        current: false,
        changes: [
            'Added: Interactive ten-frame partition challenge in Visual Components Demo',
            'Added: Section A/B selection so learners can build each addend on the ten frame',
            'Added: Check/reset/new-problem controls with targeted feedback',
            'Updated: Expansion semantic version to v2.19.0 with release notes',
        ],
    },
    {
        version: '1.10.0',
        date: '2026-02-15',
        title: 'Expansion Practice Flow Options',
        current: false,
        changes: [
            'Added: Expansion setting to auto-advance to the next question after a correct answer',
            'Added: Expansion setting to auto-focus the answer input for each new question',
            'Improved: Smoother practice flow in facts and progressive levels screens',
            'Updated: Expansion module semantic version to v2.18.0 with release notes',
        ],
    },
    {
        version: '1.9.0',
        date: '2026-02-12',
        title: 'Section Tabs - Root Cause Fixed (CSS Contrast Issue)',
        current: false,
        changes: [
            'ROOT CAUSE: Section tabs were ALWAYS rendering but invisible due to low contrast',
            'PROBLEM: Dark gray buttons (#1a1a1a) on dark background (#0a0a0a) with no visible borders',
            'WHAT WE TRIED (v1.8.0-1.8.3): HTML fallbacks, !important overrides, explicit sizing - none worked because tabs WERE rendering',
            'SOLUTION: Applied proper color contrast - lighter gray (#2a2a2a) with visible borders and teal accent for active state',
            'FIXED: Tabs now clearly visible with #ccc text on #2a2a2a background',
            'FIXED: Active tab uses teal accent (#4ecdc4) with dark text for maximum visibility',
            'FIXED: Restored proper button styling (was orange during debugging)',
            'PREVENTION: Added CSS comment warning about contrast requirements',
            'LESSON: Low contrast CSS can make elements invisible even when DOM/JS work correctly',
        ],
    },
    {
        version: '1.8.2',
        date: '2026-02-12',
        title: 'Section Tabs - Simplified CSS Approach',
        current: false,
        changes: [
            'VERIFICATION: Red background added to section-tabs to confirm CSS loading',
            'Fixed: Completely rewrote section tab CSS with explicit values',
            'Removed: All !important declarations for cleaner code',
            'Changed: Explicit pixel values for height (52px), font-size (16px), padding',
            'Changed: Explicit hex colors instead of CSS variables for debugging',
        ],
    },
    {
        version: '1.8.1',
        date: '2026-02-12',
        title: 'Section Tabs Display Fix',
        current: false,
        changes: [
            'Fixed: Section tab buttons now display properly with min-height and flex centering',
            'Fixed: Removed appearance: none which was causing button collapse in some browsers',
            'Fixed: Buttons now use flex display with centered content for reliable rendering',
            'Improved: Section tabs work correctly across all browsers and devices',
        ],
    },
    {
        version: '1.8.0',
        date: '2026-02-12',
        title: 'Section Tabs Fix',
        current: false,
        changes: [
            'Fixed: Section tabs (Number Sense / Times Tables) now reliably display on all browsers',
            'Moved: Section tab CSS to main stylesheet with inline style fallback for cache resilience',
            'Improved: TimesTables init wrapped in error handling to prevent startup failures',
        ],
    },
    {
        version: '1.7.0',
        date: '2026-02-12',
        title: 'Improved Section Tabs & App Guide',
        current: false,
        changes: [
            'Improved: Section tabs are now larger and more prominent with teal border and bigger font',
            'Added: GUIDE.md — comprehensive app documentation covering all features, levels, mastery, and settings',
        ],
    },
    {
        version: '1.6.0',
        date: '2026-02-12',
        title: 'Multiplication & Division Facts',
        current: false,
        changes: [
            'Added: Times Tables section with tables 1-20 for multiplication & division facts',
            'Added: Custom fact table support — add any number beyond 1-20',
            'Added: Level-based progression (L1-L5) with division introduced at L3+',
            'Added: Section tabs on home screen to switch between Number Sense and Times Tables',
            'Added: Auto-practice for times tables (weighted by mastery deficit)',
            'Added: Times table progress in stats dashboard with question history drill-down',
            'Updated: Answer input supports 5-digit results for larger multiplications',
        ],
    },
    {
        version: '1.5.0',
        date: '2026-02-12',
        title: 'Avatar Fix, Question History & Teacher Unlock',
        current: false,
        changes: [
            'Fixed: Avatar no longer covers quiz UI — moved into feedback row',
            'Added: Per-strategy question history dropdown showing variations, frequency, correctness, and avg time',
            'Added: Teacher module unlock — teachers can unlock locked strategies for any student',
            'Updated: Unlock logic in engine and home screen respects teacher overrides',
        ],
    },
    {
        version: '1.4.0',
        date: '2026-02-11',
        title: 'Module Pattern Refactor',
        current: false,
        changes: [
            'Refactored: Split app.js into app-core.js, app-quiz.js, and app-screens.js using Object.assign module pattern',
            'Improved: Each module is under 280 lines for easier maintenance',
            'Updated: Service worker cache list for new file structure',
        ],
    },
    {
        version: '1.3.0',
        date: '2026-02-11',
        title: 'Major Feature Update',
        current: false,
        changes: [
            'Added: Session drill-down — tap sessions to see questions, answers, and times',
            'Added: Larger interactive visual aids — tappable dots, clickable number lines',
            'Added: Teacher/parent dashboard with PIN protection and player comparison',
            'Added: Spaced repetition (SM-2 algorithm) with toggle in settings',
            'Added: Offline PWA support — installable on tablets with service worker',
            'Added: CSV and PDF export alongside JSON',
            'Added: Goal setting with strategy targets, deadlines, and visual progress',
            'Added: Visual stats dashboard with bar charts, line charts, and sparklines',
            'Added: Encouraging messages and avatar character reacting to performance',
            'Added: Daily challenge mode with streak tracking',
            'Added: Incorrect questions flagged for automatic retry',
            'Added: Weakest strategy indicator and response time trends',
            'Added: Strategy intervention with worked examples after 2+ wrong in a row',
            'Added: Practice mode (no timer) from intervention popups',
            'Added: Settings screen with toggles for all features',
        ],
    },
    {
        version: '1.2.0',
        date: '2026-02-11',
        title: 'Duplicate Question Fix',
        current: false,
        changes: [
            'Fixed: Questions no longer repeat within a session',
            'Added: Session-level deduplication with retry logic for unique question generation',
        ],
    },
    {
        version: '1.1.0',
        date: '2026-02-11',
        title: 'Export Fix & Version History',
        current: false,
        changes: [
            'Fixed: JSON export now includes full question log data (question text, answers, time per question)',
            'Added: Question log index for efficient data retrieval',
            'Added: Version history screen accessible from the app',
            'Added: Changelog viewer with full release archive',
            'Added: Source snapshots archived per version in /versions/ folder',
        ],
    },
    {
        version: '1.0.0',
        date: '2026-02-11',
        title: 'Initial Release',
        current: false,
        changes: [
            'All 12 mental math strategy problem generators',
            'Adaptive difficulty engine with time and accuracy metrics',
            'Firebase-compatible data layer with localStorage',
            'Session logging and per-question progress tracking',
            'Progress dashboard and stats view',
            'Teaching/hint system with visual aids for struggling students',
            'Multi-player support with isolated data per player',
            'Mobile-optimised responsive design with numpad input',
            'JSON data export for teacher review',
        ],
    },
];
